# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Arma_colSums <- function(x) {
    .Call(`_disag_v8_Arma_colSums`, x)
}

fitCpp <- function(rho, Qty, R, RtR, r, N, b0, S1, S2, S3, S4, S5, S6, S7, S8, S9, sldiagA, it) {
    .Call(`_disag_v8_fitCpp`, rho, Qty, R, RtR, r, N, b0, S1, S2, S3, S4, S5, S6, S7, S8, S9, sldiagA, it)
}

hbCpp <- function(rho, Qty, R, RtR, r, N, b0, S1, S2, S3, S4, S5, S6, S7, S8, S9) {
    .Call(`_disag_v8_hbCpp`, rho, Qty, R, RtR, r, N, b0, S1, S2, S3, S4, S5, S6, S7, S8, S9)
}

ll_at_min <- function(rho, Qty, R, RtR, r, N, b0, S1, S2, S3, S4, S5, S6, S7, S8, S9, sldiagA) {
    .Call(`_disag_v8_ll_at_min`, rho, Qty, R, RtR, r, N, b0, S1, S2, S3, S4, S5, S6, S7, S8, S9, sldiagA)
}

getIndex <- function(v, b) {
    .Call(`_disag_v8_getIndex`, v, b)
}

getRowIndex_NA <- function(m) {
    .Call(`_disag_v8_getRowIndex_NA`, m)
}

tpmm_agg_noblock_fast <- function(Xs, groups, blocks, b) {
    .Call(`_disag_v8_tpmm_agg_noblock_fast`, Xs, groups, blocks, b)
}

tpmm_vec_q_noblock <- function(Xs, b, type) {
    .Call(`_disag_v8_tpmm_vec_q_noblock`, Xs, b, type)
}

tpmm_vec_noblock <- function(Xs, b) {
    .Call(`_disag_v8_tpmm_vec_noblock`, Xs, b)
}

